name: EVCA
channels:
  - pytorch
  - defaults
  - anaconda
dependencies:
  - blas
  - bottleneck
  - brotli
  - brotli-bin
  - bzip2
  - ca-certificates
  - certifi
  - cffi
  - charset-normalizer
  - contourpy
  - cycler
  - filelock
  - fonttools
  - freetype
  - fsspec
  - gmp
  - gmpy2
  - idna
  - jinja2
  - jpeg
  - kiwisolver
  - lcms2
  - lerc
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcxx
  - libdeflate
  - libffi
  - libgfortran
  - libgfortran5
  - libjpeg-turbo
  - libopenblas
  - libpng
  - libprotobuf
  - libtiff
  - libuv
  - libwebp-base
  - llvm-openmp
  - lz4-c
  - markupsafe
  - matplotlib
  - matplotlib-base
  - mpc
  - mpfr
  - mpmath
  - munkres
  - ncurses
  - networkx
  - ninja
  - ninja-base
  - numexpr
  - numpy
  - numpy-base
  - openjpeg
  - openssl
  - packaging
  - pandas
  - pillow
  - pip
  - pycparser
  - pyparsing
  - python=3.11.7
  - python-dateutil
  - python-tzdata
  - pytorch
  - pytz
  - pyyaml
  - readline
  - requests
  - setuptools
  - six
  - sleef
  - sqlite
  - sympy
  - tk
  - torchaudio
  - torchvision
  - tornado
  - typing-extensions
  - typing_extensions
  - tzdata
  - urllib3
  - wheel
  - xz
  - yaml
  - zlib
  - zstd
  - pip:
      - torch-dct
